import type { Metadata } from "next";
import { Noto_Sans, Montserrat } from 'next/font/google'
import "./globals.css";

const noto_sans = Noto_Sans({
  weight: ['300', '400', '700', '900'],
  subsets: ['latin'],
  display: 'auto'
})

const montserrat = Montserrat({
  weight: ['300', '400', '700', '900'],
  subsets: ['latin'],
  display: 'auto'
})


export const metadata: Metadata = {
  icons: [
    { rel: 'icon', url: '/favicon.ico' }
  ],
  title: "Peanxtt's Github Page",
  description: "Generated by github page",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} ${noto_sans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
